from django.apps import AppConfig

# This file is generated by Django when you create a new app.
# It defines the configuration for the app.


class CoreConfig(AppConfig):
    '''
    Configuration for the core app.
    '''
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'core'
