# Generated by Django 4.2.28 on 2026-03-16 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication', '0002_alter_publication_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='journalists',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'journalist'}, related_name='publications_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
