# Generated by Django 4.2.28 on 2026-03-17 00:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication', '0003_publication_journalists'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='pending_editors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'editor'}, related_name='editor_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
