# Generated by Django 4.2.28 on 2026-03-18 23:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication', '0004_publication_pending_editors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='editor',
        ),
        migrations.AddField(
            model_name='publication',
            name='editors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'editor_status': 'approved', 'role': 'editor'}, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
