# Generated by Django 4.2.28 on 2026-03-18 23:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication', '0005_remove_publication_editor_publication_editors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='editors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'editor_status': 'approved', 'role': 'editor'}, to=settings.AUTH_USER_MODEL),
        ),
    ]
