# Generated by Django 4.2.28 on 2026-03-19 02:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication', '0006_alter_publication_editors'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='pending_journalists',
            field=models.ManyToManyField(blank=True, related_name='journalist_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
