# Generated by Django 4.2.28 on 2026-03-23 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0007_publication_pending_journalists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='journalists',
            new_name='approved_journalists',
        ),
    ]
