# Generated by Django 4.2.28 on 2026-03-30 22:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication', '0008_rename_journalists_publication_approved_journalists'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='publication',
            name='editors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'editor_status': 'approved', 'role': 'editor'}, related_name='editor_publications', to=settings.AUTH_USER_MODEL),
        ),
    ]
