from django.apps import AppConfig

# This file is generated by Django when you create a new app. It defines the
# configuration for the app.


class UsersConfig(AppConfig):
    '''
    Configuration for the users app.
    '''
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'users'

    def ready(self):
        import users.signals  # noqa: F401 Import signals to connect them
